export const germanCities = [
  "Aach",
  "Aachen",
  "Aalen",
  "Abenberg",
  "Abensberg",
  "Achern",
  "Achim",
  "Adelsheim",
  "Adenau",
  "Adorf",
  "Ahaus",
  "Ahlen",
  "Ahrensburg",
  "Aichach",
  "Aichtal",
  "Aken",
  "Albstadt",
  "Alfeld",
  "Allendorf",
  "Allstedt",
  "Alpirsbach",
  "Alsdorf",
  "Alsfeld",
  "Alsleben",
  "Altdorf bei Nürnberg",
  "Altena",
  "Altenberg",
  "Altenburg",
  "Altenkirchen",
  "Altensteig",
  "Altentreptow",
  "Altlandsberg",
  "Altötting",
  "Alzenau",
  "Alzey",
  "Amberg",
  "Amöneburg",
  "Amorbach",
  "Amt Creuzburg",
  "An der Schmücke",
  "Andernach",
  "Angermünde",
  "Anklam",
  "Annaberg-Buchholz",
  "Annaburg",
  "Annweiler am Trifels",
  "Ansbach",
  "Apolda",
  "Arendsee",
  "Arneburg",
  "ArnisArnæs",
  "Arnsberg",
  "Arnstadt",
  "Arnstein",
  "Artern",
  "Arzberg",
  "Aschaffenburg",
  "Aschersleben",
  "Asperg",
  "Aßlar",
  "Attendorn",
  "Aub",
  "Aue-Bad Schlema",
  "Auerbach",
  "Auerbach in der Oberpfalz",
  "Augsburg",
  "Augustusburg",
  "Aulendorf",
  "Auma-Weidatal",
  "Aurich",
  "Babenhausen",
  "Bacharach",
  "Backnang",
  "Bad Aibling",
  "Bad Arolsen",
  "Bad Belzig",
  "Bad Bentheim",
  "Bad Bergzabern",
  "Bad Berka",
  "Bad Berleburg",
  "Bad Berneck i.Fichtelgebirge",
  "Bad Bevensen",
  "Bad Bibra",
  "Bad Blankenburg",
  "Bad Bramstedt",
  "Bad Breisig",
  "Bad Brückenau",
  "Bad Buchau",
  "Bad Camberg",
  "Bad Doberan",
  "Bad Driburg",
  "Bad Düben",
  "Bad Dürkheim",
  "Bad Dürrenberg",
  "Bad Dürrheim",
  "Bad Elster",
  "Bad Ems",
  "Bad Fallingbostel",
  "Bad Frankenhausen",
  "Bad Freienwalde",
  "Bad Friedrichshall",
  "Bad Gandersheim",
  "Bad Gottleuba-Berggießhübel",
  "Bad Griesbach im Rottal",
  "Bad Harzburg",
  "Bad Herrenalb",
  "Bad Hersfeld",
  "Bad Homburg v. d. Höhe",
  "Bad Honnef",
  "Bad Hönningen",
  "Bad Iburg",
  "Bad Karlshafen",
  "Bad Kissingen",
  "Bad König",
  "Bad Königshofen",
  "Bad Köstritz",
  "Bad Kötzting",
  "Bad Kreuznach",
  "Bad Krozingen",
  "Bad Laasphe",
  "Bad Langensalza",
  "Bad Lauchstädt",
  "Bad Lausick",
  "Bad Lauterberg",
  "Bad Liebenstein",
  "Bad Liebenwerda",
  "Bad Liebenzell",
  "Bad Lippspringe",
  "Bad Lobenstein",
  "Bad Marienberg",
  "Bad Mergentheim",
  "Bad Münder",
  "Bad Münstereifel",
  "Bad Muskau",
  "Bad Nauheim",
  "Bad Nenndorf",
  "Bad Neuenahr-Ahrweiler",
  "Bad Neustadt an der Saale",
  "Bad Oeynhausen",
  "Bad Oldesloe",
  "Bad Orb",
  "Bad Pyrmont",
  "Bad Rappenau",
  "Bad Reichenhall",
  "Bad Rodach",
  "Bad Sachsa",
  "Bad Säckingen",
  "Bad Salzdetfurth",
  "Bad Salzuflen",
  "Bad Salzungen",
  "Bad Saulgau",
  "Bad Schandau",
  "Bad Schmiedeberg",
  "Bad Schussenried",
  "Bad Schwalbach",
  "Bad Schwartau",
  "Bad Segeberg",
  "Bad Sobernheim",
  "Bad Soden",
  "Bad Soden-Salmünster",
  "Bad Sooden-Allendorf",
  "Bad Staffelstein",
  "Bad Sulza",
  "Bad Sülze",
  "Bad Teinach-Zavelstein",
  "Bad Tennstedt",
  "Bad Tölz",
  "Bad Urach",
  "Bad Vilbel",
  "Bad Waldsee",
  "Bad Wildbad",
  "Bad Wildungen",
  "Bad Wilsnack",
  "Bad Wimpfen",
  "Bad Windsheim",
  "Bad Wörishofen",
  "Bad Wünnenberg",
  "Bad Wurzach",
  "Baden-Baden",
  "Baesweiler",
  "Baiersdorf",
  "Balingen",
  "Ballenstedt",
  "Balve",
  "Bamberg",
  "Barby",
  "Bargteheide",
  "Barmstedt",
  "Bärnau",
  "Barntrup",
  "Barsinghausen",
  "Barth",
  "Baruth/Mark",
  "Bassum",
  "Battenberg",
  "Baumholder",
  "Baunach",
  "Baunatal",
  "Bautzen",
  "Bayreuth",
  "Bebra",
  "Beckum",
  "Bedburg",
  "Beelitz",
  "Beeskow",
  "Beilngries",
  "Beilstein",
  "Belgern-Schildau",
  "Bendorf",
  "Bensheim",
  "Berching",
  "Berga",
  "Bergen",
  "Bergen auf Rügen",
  "Bergheim",
  "Bergisch Gladbach",
  "Bergkamen",
  "Bergneustadt",
  "Berlin",
  "Bernau bei Berlin",
  "Bernburg",
  "Bernkastel-Kues",
  "Bernsdorf",
  "Bernstadt auf dem Eigen",
  "Bersenbrück",
  "Besigheim",
  "Betzdorf",
  "Betzenstein",
  "Beverungen",
  "Bexbach",
  "Biberach an der Riss",
  "Biedenkopf",
  "Bielefeld",
  "Biesenthal",
  "Bietigheim-Bissingen",
  "Billerbeck",
  "Bingen am Rhein",
  "Birkenfeld",
  "Bischofsheim i.d.Rhön",
  "Bischofswerda",
  "Bismark",
  "Bitburg",
  "Bitterfeld-Wolfen",
  "Blankenburg",
  "Blankenhain",
  "Blaubeuren",
  "Blaustein",
  "Bleckede",
  "Bleicherode",
  "Blieskastel",
  "Blomberg",
  "Blumberg",
  "Bobingen",
  "Böblingen",
  "Bocholt",
  "Bochum",
  "Bockenem",
  "Bodenwerder",
  "Bogen",
  "Böhlen",
  "Boizenburg",
  "Bonn",
  "Bonndorf im Schwarzwald",
  "Bönnigheim",
  "Bopfingen",
  "Boppard",
  "Borgentreich",
  "Borgholzhausen",
  "Borken",
  "Borkum",
  "Borna",
  "Bornheim",
  "Bottrop",
  "Boxberg",
  "Brackenheim",
  "Brake",
  "Brakel",
  "Bramsche",
  "Brand-Erbisdorf",
  "Brandenburg an der Havel",
  "Brandis",
  "Braubach",
  "Braunfels",
  "Braunlage",
  "Bräunlingen",
  "Braunsbedra",
  "Breckerfeld",
  "BredstedtBräist / Bredsted",
  "Breisach",
  "Bremen",
  "Bremerhaven",
  "Bremervörde",
  "Bretten",
  "Breuberg",
  "Brilon",
  "Brotterode-Trusetal",
  "Bruchköbel",
  "Bruchsal",
  "Brück",
  "Brüel",
  "Brühl",
  "Brunsbüttel",
  "Brunswick",
  "Brüssow",
  "Buchen",
  "Buchholz in der Nordheide",
  "Buchloe",
  "Bückeburg",
  "Buckow",
  "Büdelsdorf",
  "Büdingen",
  "Bühl",
  "Bünde",
  "Büren",
  "Burg",
  "Burg Stargard",
  "Burgau",
  "Burgbernheim",
  "Burgdorf",
  "Bürgel",
  "Burghausen",
  "Burgkunstadt",
  "Burglengenfeld",
  "Burgstädt",
  "Burgwedel",
  "Burladingen",
  "Burscheid",
  "Bürstadt",
  "Butzbach",
  "Bützow",
  "Calau",
  "Calbe",
  "Calw",
  "Castrop-Rauxel",
  "Celle",
  "Cham",
  "Chemnitz",
  "Clausthal-Zellerfeld",
  "Clingen",
  "Cloppenburg",
  "Coburg",
  "Cochem",
  "Coesfeld",
  "Colditz",
  "Cologne",
  "Constance",
  "Coswig",
  "Cottbus/Chóśebuz",
  "Crailsheim",
  "Creglingen",
  "Creußen",
  "Crimmitschau",
  "Crivitz",
  "Cuxhaven",
  "Daaden",
  "Dachau, Bavaria",
  "Dahlen",
  "Dahme",
  "Dahn",
  "Damme",
  "Dannenberg",
  "Dargun",
  "Darmstadt",
  "Dassel",
  "Dassow",
  "Datteln",
  "Daun",
  "Deggendorf",
  "Deidesheim",
  "Delbrück",
  "Delitzsch",
  "Delmenhorst",
  "Demmin",
  "Dessau-Roßlau",
  "Detmold",
  "Dettelbach",
  "Dieburg",
  "Diemelstadt",
  "Diepholz",
  "Dierdorf",
  "Dietenheim",
  "Dietfurt a.d. Altmühl",
  "Dietzenbach",
  "Diez, Germany",
  "Dillenburg",
  "Dillingen",
  "Dillingen an der Donau",
  "Dingelstädt",
  "Dingolfing",
  "Dinkelsbühl",
  "Dinklage",
  "Dinslaken",
  "Dippoldiswalde",
  "Dissen, Lower Saxony",
  "Ditzingen",
  "Döbeln",
  "Doberlug-Kirchhain",
  "Döbern",
  "Dohna",
  "Dömitz",
  "Dommitzsch",
  "Donaueschingen",
  "Donauwörth",
  "Donzdorf",
  "Dorfen",
  "Dormagen",
  "Dornburg-Camburg",
  "Dornhan",
  "Dornstetten",
  "Dorsten",
  "Dortmund",
  "Dransfeld",
  "Drebkau",
  "Dreieich",
  "Drensteinfurt",
  "Dresden",
  "Drolshagen",
  "Duderstadt",
  "Duisburg",
  "Dülmen",
  "Düren",
  "Düsseldorf",
  "Ebeleben",
  "Eberbach",
  "Ebermannstadt",
  "Ebern",
  "Ebersbach an der Fils",
  "Ebersbach-Neugersdorf",
  "Ebersberg",
  "Eberswalde",
  "Eckartsberga",
  "Eckernförde Eckernföör, Egernførde",
  "Edenkoben",
  "Egeln",
  "Eggenfelden",
  "Eggesin",
  "Ehingen",
  "Ehrenfriedersdorf",
  "Eibelstadt",
  "Eibenstock",
  "Eichstätt",
  "Eilenburg",
  "Einbeck",
  "Eisenach",
  "Eisenberg",
  "Eisenhüttenstadt",
  "Eisfeld",
  "Eisleben",
  "Eislingen",
  "Ellingen",
  "Ellrich",
  "Ellwangen",
  "Elmshorn",
  "Elsdorf",
  "Elsfleth",
  "Elsterberg",
  "Elsterwerda",
  "Elstra",
  "Elterlein",
  "Eltmann",
  "Eltville",
  "Elzach",
  "Elze",
  "Emden",
  "Emmelshausen",
  "Emmendingen",
  "Emmerich",
  "Emsdetten",
  "Endingen",
  "Engen",
  "Enger",
  "Ennepetal",
  "Ennigerloh",
  "Eppelheim",
  "Eppingen",
  "Eppstein",
  "Erbach",
  "Erbendorf",
  "Erding",
  "Erftstadt",
  "Erfurt",
  "Erkelenz",
  "Erkner",
  "Erkrath",
  "Erlangen",
  "Erlenbach a.Main",
  "Erlensee",
  "Erwitte",
  "Eschborn",
  "Eschenbach in der Oberpfalz",
  "Eschershausen",
  "Eschwege",
  "Eschweiler",
  "Espelkamp",
  "Essen",
  "Esslingen am Neckar",
  "Ettenheim",
  "Ettlingen",
  "Euskirchen",
  "Eutin",
  "Falkenberg/Elster",
  "Falkensee",
  "Falkenstein",
  "Falkenstein/Harz",
  "Fehmarn",
  "Fellbach",
  "Felsberg",
  "Feuchtwangen",
  "Filderstadt",
  "Finsterwalde",
  "Fladungen",
  "Flensburg",
  "Flöha",
  "Flörsheim am Main",
  "Florstadt",
  "Forchheim",
  "Forchtenberg",
  "Forst (Lausitz)",
  "Frankenau",
  "Frankenberg",
  "Frankenthal (Pfalz)",
  "Frankfurt (Oder)",
  "Frankfurt am Main",
  "Franzburg",
  "Frauenstein",
  "Frechen",
  "Freiberg",
  "Freiberg am Neckar",
  "Freiburg im Breisgau",
  "Freilassing",
  "Freinsheim",
  "Freising",
  "Freital",
  "Freren",
  "Freudenberg",
  "Freudenstadt",
  "Freyburg",
  "Freystadt",
  "Freyung",
  "Fridingen",
  "Friedberg",
  "Friedland",
  "Friedrichroda",
  "Friedrichsdorf",
  "Friedrichshafen",
  "FriedrichstadtFrederiksstad",
  "Friedrichsthal",
  "Friesack",
  "Friesoythe",
  "Fritzlar",
  "Frohburg",
  "Fröndenberg",
  "Fulda",
  "Fürstenau",
  "Fürstenberg",
  "Fürstenfeldbruck",
  "Fürstenwalde/Spree",
  "Fürth",
  "Furth im Wald",
  "Furtwangen im Schwarzwald",
  "Füssen",
  "Gadebusch",
  "Gaggenau",
  "Gaildorf",
  "Gammertingen",
  "Garbsen",
  "Garching bei München",
  "Gardelegen",
  "Garding",
  "Gartz",
  "Garz",
  "Gau-Algesheim",
  "Gebesee",
  "Gedern",
  "Geesthacht",
  "Geestland",
  "Gefell",
  "Gefrees",
  "Gehrden",
  "Geilenkirchen",
  "Geisa",
  "Geiselhöring",
  "Geisenfeld",
  "Geisenheim",
  "Geisingen",
  "Geislingen",
  "Geislingen an der Steige",
  "Geithain",
  "Geldern",
  "Gelnhausen",
  "Gelsenkirchen",
  "Gemünden",
  "Gemünden am Main",
  "Gengenbach",
  "Genthin",
  "Georgsmarienhütte",
  "Gera",
  "Gerabronn",
  "Gerbstedt",
  "Geretsried",
  "Geringswalde",
  "Gerlingen",
  "Germering",
  "Germersheim",
  "Gernsbach",
  "Gernsheim",
  "Gerolstein",
  "Gerolzhofen",
  "Gersfeld",
  "Gersthofen",
  "Gescher",
  "Geseke",
  "Gevelsberg",
  "Geyer",
  "Giengen",
  "Giessen",
  "Gifhorn",
  "Ginsheim-Gustavsburg",
  "Gladbeck",
  "Gladenbach",
  "Glashütte",
  "Glauchau",
  "Glinde",
  "GlücksburgLyksborg",
  "Glückstadt",
  "Gnoien",
  "Goch",
  "Goldberg",
  "Goldkronach",
  "Golßen",
  "Gommern",
  "Göppingen",
  "Görlitz",
  "Goslar",
  "Gößnitz",
  "Gotha",
  "Göttingen",
  "Grabow",
  "Grafenau",
  "Gräfenberg, Bavaria",
  "Gräfenhainichen",
  "Gräfenthal",
  "Grafenwöhr",
  "Grafing bei München",
  "Gransee",
  "Grebenau",
  "Grebenstein",
  "Greding",
  "Greifswald",
  "Greiz",
  "Greußen",
  "Greven",
  "Grevenbroich",
  "Grevesmühlen",
  "Griesheim",
  "Grimma",
  "Grimmen",
  "Gröditz",
  "Groitzsch",
  "Gronau",
  "Gröningen",
  "Groß-Bieberau",
  "Groß-Gerau",
  "Groß-Umstadt",
  "Großalmerode",
  "Großbottwar",
  "Großbreitenbach",
  "Großenhain",
  "Großräschen",
  "Großröhrsdorf",
  "Großschirma",
  "Grünberg",
  "Grünhain-Beierfeld",
  "Grünsfeld",
  "Grünstadt",
  "Guben",
  "Gudensberg",
  "Güglingen",
  "Gummersbach",
  "Gundelfingen an der Donau",
  "Gundelsheim",
  "Günzburg",
  "Gunzenhausen",
  "Güsten",
  "Güstrow",
  "Gütersloh",
  "Gützkow",
  "Haan",
  "Hachenburg",
  "Hadamar",
  "Hagen",
  "Hagenbach",
  "Hagenow",
  "Haiger",
  "Haigerloch",
  "Hainichen",
  "Haiterbach",
  "Halberstadt",
  "Haldensleben",
  "Halle",
  "Halle (Saale)",
  "Hallenberg",
  "Hallstadt",
  "Haltern am See",
  "Halver",
  "Hamburg",
  "Hamelin",
  "Hamm",
  "Hammelburg",
  "Hamminkeln",
  "Hanau",
  "Hann. Münden",
  "Hanover",
  "Hanseatic City of Buxtehude",
  "Hanseatic City of Korbach",
  "Hanseatic City of Stade",
  "Harburg",
  "Hardegsen",
  "Haren, Germany",
  "Harsewinkel",
  "Hartenstein",
  "Hartha",
  "Harzgerode",
  "Haselünne",
  "Haslach im Kinzigtal",
  "Haßfurt",
  "Hattersheim am Main",
  "Hattingen",
  "Hatzfeld",
  "Hausach",
  "Hauzenberg",
  "Havelberg",
  "Havelsee",
  "Hayingen",
  "Hechingen",
  "Hecklingen",
  "Heide",
  "Heideck",
  "Heidelberg",
  "Heidenau",
  "Heidenheim an der Brenz",
  "Heilbad Heiligenstadt",
  "Heilbronn",
  "Heiligenhafen",
  "Heiligenhaus",
  "Heilsbronn",
  "Heimbach",
  "Heimsheim",
  "Heinsberg",
  "Heitersheim",
  "Heldburg",
  "Helmbrechts",
  "Helmstedt",
  "Hemau",
  "Hemer",
  "Hemmingen",
  "Hemmoor",
  "Hemsbach",
  "Hennef",
  "Hennigsdorf",
  "Heppenheim",
  "Herbolzheim",
  "Herborn, Hesse",
  "Herbrechtingen",
  "Herbstein",
  "Herdecke",
  "Herdorf",
  "Herford",
  "Heringen",
  "Hermeskeil",
  "Hermsdorf",
  "Herne city",
  "Herrenberg",
  "Herrieden",
  "Herrnhut",
  "Hersbruck",
  "Herten",
  "Herzberg",
  "Herzberg am Harz",
  "Herzogenaurach",
  "Herzogenrath",
  "Hessisch Lichtenau",
  "Hessisch Oldendorf",
  "Hettingen",
  "Hettstedt",
  "Heubach",
  "Heusenstamm",
  "Hilchenbach",
  "Hildburghausen",
  "Hilden",
  "Hildesheim",
  "Hillesheim",
  "Hilpoltstein",
  "Hirschau",
  "Hirschberg",
  "Hirschhorn",
  "Hitzacker",
  "Hochheim am Main",
  "Höchstadt",
  "Höchstädt an der Donau",
  "Hockenheim",
  "Hof",
  "Hofgeismar",
  "Hofheim in Unterfranken",
  "Hofheim, Hesse",
  "Hohen Neuendorf",
  "Hohenberg a.d.Eger",
  "Hohenleuben",
  "Hohenmölsen",
  "Hohenstein-Ernstthal",
  "Hohnstein",
  "Höhr-Grenzhausen",
  "Hollfeld",
  "Holzgerlingen",
  "Holzminden",
  "Homberg",
  "Homburg",
  "Horb am Neckar",
  "Horn-Bad Meinberg",
  "Hornbach",
  "Hornberg",
  "Hörstel",
  "Horstmar",
  "Höxter",
  "Hoya",
  "Hoyerswerda",
  "Hückelhoven",
  "Hückeswagen",
  "Hüfingen",
  "Hünfeld",
  "Hungen",
  "Hürth",
  "Husum",
  "Ibbenbüren",
  "Ichenhausen",
  "Idar-Oberstein",
  "Idstein",
  "Illertissen",
  "Ilmenau",
  "Ilsenburg",
  "Ilshofen",
  "Immenhausen",
  "Immenstadt",
  "Ingelfingen",
  "Ingelheim am Rhein",
  "Ingolstadt",
  "Iphofen",
  "Iserlohn",
  "Isny im Allgäu",
  "Isselburg",
  "Itzehoe",
  "Jarmen",
  "Jena",
  "Jerichow",
  "Jessen",
  "Jever",
  "Joachimsthal",
  "Johanngeorgenstadt",
  "Jöhstadt",
  "Jüchen",
  "Jülich",
  "Jüterbog",
  "Kaarst",
  "Kahla",
  "Kaisersesch",
  "Kaiserslautern",
  "Kalbe, Saxony-Anhalt",
  "Kalkar",
  "Kaltenkirchen",
  "Kaltennordheim",
  "Kamen",
  "Kamenz",
  "Kamp-Lintfort",
  "Kandel",
  "Kandern",
  "KappelnKappel",
  "Karben",
  "Karlsruhe",
  "Karlstadt am Main",
  "Kassel",
  "Kastellaun",
  "Katzenelnbogen",
  "Kaub",
  "Kaufbeuren",
  "Kehl",
  "Kelbra",
  "Kelheim",
  "Kelkheim",
  "Kellinghusen",
  "Kelsterbach",
  "Kemberg",
  "Kemnath",
  "Kempen",
  "Kempten",
  "Kenzingen",
  "Kerpen",
  "Ketzin",
  "Kevelaer",
  "Kiel",
  "Kierspe",
  "Kirchberg",
  "Kirchberg an der Jagst",
  "Kirchen",
  "Kirchenlamitz",
  "Kirchhain",
  "Kirchheim unter Teck",
  "Kirchheimbolanden",
  "Kirn",
  "Kirtorf",
  "Kitzingen",
  "Kitzscher",
  "Kleve",
  "Klingenberg am Main",
  "Klingenthal",
  "Klötze",
  "Klütz",
  "Knittlingen",
  "Koblenz",
  "Kolbermoor",
  "Kölleda",
  "Königs Wusterhausen",
  "Königsberg in Bayern",
  "Königsbrück",
  "Königsbrunn",
  "Königsee",
  "Königslutter",
  "Königstein",
  "Königstein im Taunus",
  "Königswinter",
  "Könnern",
  "Konz",
  "Korntal-Münchingen",
  "Kornwestheim",
  "Korschenbroich",
  "Köthen",
  "Kraichtal",
  "Krakow am See",
  "Kranichfeld",
  "Krautheim",
  "Krefeld",
  "Kremmen",
  "Krempe",
  "Kreuztal",
  "Kronach",
  "Kronberg im Taunus",
  "Kröpelin",
  "Kroppenstedt",
  "Krumbach",
  "Kühlungsborn",
  "Kulmbach",
  "Külsheim",
  "Künzelsau",
  "Kupferberg",
  "Kuppenheim",
  "Kusel",
  "Kyllburg",
  "Kyritz",
  "Laage",
  "Laatzen",
  "Ladenburg",
  "Lage",
  "Lahnstein",
  "Lahr",
  "Laichingen",
  "Lambrecht, Rhineland-Palatinate",
  "Lampertheim",
  "Landau an der Isar",
  "Landau in der Pfalz",
  "Landsberg",
  "Landsberg am Lech",
  "Landshut",
  "Landstuhl",
  "Langelsheim",
  "Langen, Hesse",
  "Langenau",
  "Langenburg",
  "Langenfeld",
  "Langenhagen",
  "Langenselbold",
  "Langenzenn",
  "Lassan",
  "Laubach",
  "Laucha an der Unstrut",
  "Lauchhammer",
  "Lauchheim",
  "Lauda-Königshofen",
  "Lauenburg",
  "Lauf an der Pegnitz",
  "Laufen",
  "Laufenburg",
  "Lauffen",
  "Lauingen",
  "Laupheim",
  "Lauscha",
  "Lauta",
  "Lauter-Bernsbach",
  "Lauterbach",
  "Lauterecken",
  "Lauterstein",
  "Lebach",
  "Lebus",
  "Leer",
  "Lehesten",
  "Lehrte",
  "Leichlingen",
  "Leimen",
  "Leinefelde-Worbis",
  "Leinfelden-Echterdingen",
  "Leingarten",
  "Leipheim",
  "Leipzig",
  "Leisnig",
  "Lemgo",
  "Lengenfeld",
  "Lengerich",
  "Lennestadt",
  "Lenzen",
  "Leonberg",
  "Leun",
  "Leuna",
  "Leutenberg",
  "Leutershausen",
  "Leutkirch im Allgäu",
  "Leverkusen",
  "Lich",
  "Lichtenau",
  "Lichtenberg",
  "Lichtenfels",
  "Lichtenstein",
  "Liebenau",
  "Liebenwalde",
  "Lieberose",
  "Liebstadt",
  "Limbach-Oberfrohna",
  "Limburg an der Lahn",
  "Lindau",
  "Linden",
  "Lindenberg im Allgäu",
  "Lindenfels",
  "Lindow",
  "Lingen (Ems)",
  "Linnich",
  "Linz am Rhein",
  "Lippstadt",
  "Löbau",
  "Löffingen",
  "Lohmar",
  "Löhne",
  "Lohne (Oldenburg)",
  "Lohr a. Main",
  "Loitz",
  "Lollar",
  "Lommatzsch",
  "Löningen",
  "Lorch",
  "Lörrach",
  "Lorsch",
  "Lößnitz",
  "Löwenstein",
  "Lübbecke",
  "Lübben/Lubin",
  "Lübbenau/Spreewald",
  "Lübeck",
  "Lübtheen",
  "Lübz",
  "Lüchow",
  "Lucka",
  "Luckau",
  "Luckenwalde",
  "Lüdenscheid",
  "Lüdinghausen",
  "Ludwigsburg",
  "Ludwigsfelde",
  "Ludwigshafen am Rhein",
  "Ludwigslust",
  "Ludwigsstadt",
  "Lugau",
  "Lügde",
  "Lüneburg",
  "Lünen",
  "Lunzenau",
  "Lütjenburg",
  "Lützen",
  "Lychen",
  "Magdala",
  "Magdeburg",
  "Mahlberg",
  "Mainbernheim",
  "Mainburg",
  "Maintal",
  "Mainz",
  "Malchin",
  "Malchow",
  "Manderscheid",
  "Mannheim",
  "Mansfeld",
  "Marbach am Neckar",
  "Marburg",
  "Marienberg",
  "Marienmünster",
  "Markdorf",
  "Markgröningen",
  "Märkisch Buchholz",
  "Markkleeberg",
  "Markneukirchen",
  "Markranstädt",
  "Marktbreit",
  "Marktheidenfeld",
  "Marktleuthen",
  "Marktoberdorf",
  "Marktredwitz",
  "Marktsteft",
  "Marl",
  "Marlow",
  "Marne",
  "Marsberg",
  "Maulbronn",
  "Maxhütte-Haidhof",
  "Mayen",
  "Mechernich",
  "Meckenheim",
  "Medebach",
  "Meerane",
  "Meerbusch",
  "Meersburg",
  "Meinerzhagen",
  "Meiningen",
  "Meisenheim",
  "Meissen",
  "Meldorf",
  "Melle",
  "Mellrichstadt",
  "Melsungen",
  "Memmingen",
  "Menden",
  "Mendig",
  "Mengen",
  "Meppen",
  "Merkendorf",
  "Merseburg",
  "Merzig",
  "Meschede",
  "Meßkirch",
  "Meßstetten",
  "Mettmann",
  "Metzingen",
  "Meuselwitz",
  "Meyenburg",
  "Michelstadt",
  "Miesbach",
  "Miltenberg",
  "Mindelheim",
  "Minden",
  "Mirow",
  "Mittenwalde",
  "Mitterteich",
  "Mittweida",
  "Möckern",
  "Möckmühl",
  "Moers",
  "Mölln",
  "Mönchengladbach",
  "Monheim",
  "Monheim am Rhein",
  "Monschau",
  "Montabaur",
  "Moosburg an der Isar",
  "Mörfelden-Walldorf",
  "Moringen",
  "Mosbach",
  "Mössingen",
  "Mücheln",
  "Mügeln",
  "Mühlacker",
  "Mühlberg",
  "Mühldorf am Inn",
  "Mühlhausen",
  "Mühlheim am Main",
  "Mühlheim an der Donau",
  "Mülheim an der Ruhr",
  "Mülheim-Kärlich",
  "Müllheim",
  "Müllrose",
  "Münchberg",
  "Müncheberg",
  "Münchenbernsdorf",
  "Munderkingen",
  "Munich",
  "Münnerstadt",
  "Münsingen",
  "Munster",
  "Münster",
  "Münstermaifeld",
  "Münzenberg",
  "Murrhardt",
  "Nabburg",
  "Nagold",
  "Naila",
  "Nassau",
  "Nastätten",
  "Nauen",
  "Naumburg",
  "Naunhof",
  "Nebra",
  "Neckarbischofsheim",
  "Neckargemünd",
  "Neckarsteinach",
  "Neckarsulm",
  "Neresheim",
  "Netphen",
  "Nettetal",
  "Netzschkau",
  "Neu-Anspach",
  "Neu-Isenburg",
  "Neu-Ulm",
  "Neubrandenburg",
  "Neubukow",
  "Neubulach",
  "Neuburg a.d. Donau",
  "Neudenau",
  "Neuenbürg",
  "Neuenburg am Rhein",
  "Neuenhaus",
  "Neuenrade",
  "Neuenstadt am Kocher",
  "Neuenstein",
  "Neuerburg",
  "Neuffen",
  "Neuhaus am Rennweg",
  "Neukalen",
  "Neukirchen",
  "Neukirchen-Vluyn",
  "Neukloster",
  "Neumark",
  "Neumarkt in der Oberpfalz",
  "Neumarkt-Sankt Veit",
  "Neumünster",
  "Neunburg vorm Wald",
  "Neunkirchen",
  "Neuötting",
  "Neuruppin",
  "Neusalza-Spremberg",
  "Neusäß",
  "Neuss",
  "Neustadt",
  "Neustadt a.d.Donau",
  "Neustadt a.d.Waldnaab",
  "Neustadt am Kulm",
  "Neustadt am Rübenberge",
  "Neustadt an der Aisch",
  "Neustadt an der Orla",
  "Neustadt an der Weinstraße",
  "Neustadt b.Coburg",
  "Neustadt in Holstein",
  "Neustadt in Sachsen",
  "Neustadt-Glewe",
  "Neustrelitz",
  "Neutraubling",
  "Neuwied",
  "Nidda",
  "Niddatal",
  "Nidderau",
  "Nideggen",
  "NiebüllNaibel / Nibøl",
  "Niedenstein",
  "Nieder-Olm",
  "Niederkassel",
  "Niedernhall",
  "Niederstetten",
  "Niederstotzingen",
  "Nieheim",
  "Niemegk",
  "Nienburg",
  "Nierstein",
  "Niesky",
  "Nittenau",
  "Norden",
  "Nordenham",
  "Norderney",
  "Norderstedt",
  "Nordhausen, Thuringia",
  "Nordhorn",
  "Nördlingen",
  "Northeim",
  "Nortorf",
  "Nossen",
  "Nottertal-Heilinger Höhen",
  "Nuremberg",
  "Nürtingen",
  "Ober-Ramstadt",
  "Oberasbach",
  "Oberharz am Brocken",
  "Oberhausen",
  "Oberhof",
  "Oberkirch",
  "Oberkochen",
  "Oberlungwitz",
  "Obermoschel",
  "Obernburg a.Main",
  "Oberndorf am Neckar",
  "Obernkirchen",
  "Oberriexingen",
  "Obertshausen",
  "Oberursel (Taunus)",
  "Oberviechtach",
  "Oberwesel",
  "Oberwiesenthal",
  "Oberzent",
  "Ochsenfurt",
  "Ochsenhausen",
  "Ochtrup",
  "Oderberg",
  "Oebisfelde-Weferlingen",
  "Oederan",
  "Oelde",
  "Oelsnitz",
  "Oer-Erkenschwick",
  "Oerlinghausen",
  "Oestrich-Winkel",
  "Oettingen in Bayern",
  "Offenbach am Main",
  "Offenburg",
  "Ohrdruf",
  "Öhringen",
  "Olbernhau",
  "Olching",
  "Oldenburg",
  "Oldenburg in Holstein",
  "Olfen",
  "Olpe",
  "Olsberg",
  "Oppenau",
  "Oppenheim",
  "Oranienbaum-Wörlitz",
  "Oranienburg",
  "Orlamünde",
  "Ornbau",
  "Ortenberg",
  "Ortrand",
  "Oschatz",
  "Oschersleben",
  "Osnabrück",
  "Osterburg",
  "Osterburken",
  "Osterfeld",
  "Osterhofen",
  "Osterholz-Scharmbeck",
  "Osterode am Harz",
  "Osterwieck",
  "Ostfildern",
  "Ostheim",
  "Osthofen",
  "Östringen",
  "Ostritz",
  "Otterberg",
  "Otterndorf",
  "Ottweiler",
  "Overath",
  "Owen",
  "Paderborn",
  "Papenburg",
  "Pappenheim",
  "Parchim",
  "Parsberg",
  "Pasewalk",
  "Passau",
  "Pattensen",
  "Pausa-Mühltroff",
  "Pegau",
  "Pegnitz",
  "Peine",
  "Peitz",
  "Penig",
  "Penkun",
  "Penzberg",
  "Penzlin",
  "Perleberg",
  "Petershagen",
  "Pfaffenhofen a.d.Ilm",
  "Pfarrkirchen",
  "Pforzheim",
  "Pfreimd",
  "Pfullendorf",
  "Pfullingen",
  "Pfungstadt",
  "Philippsburg",
  "Pinneberg",
  "Pirmasens",
  "Pirna",
  "Plattling",
  "Plau am See",
  "Plaue",
  "Plauen",
  "Plettenberg",
  "Pleystein",
  "Plochingen",
  "Plön",
  "Pockau-Lengefeld",
  "Pocking",
  "Pohlheim",
  "Polch",
  "Porta Westfalica",
  "Pößneck",
  "Potsdam",
  "Pottenstein",
  "Preetz",
  "Premnitz",
  "Prenzlau",
  "Pressath",
  "Preußisch Oldendorf",
  "Prichsenstadt",
  "Pritzwalk",
  "Prüm",
  "Puchheim",
  "Pulheim",
  "Pulsnitz",
  "Putbus",
  "Putlitz",
  "Püttlingen",
  "Quakenbrück",
  "Quedlinburg",
  "Querfurt",
  "Quickborn",
  "Rabenau",
  "Radeberg",
  "Radebeul",
  "Radeburg",
  "Radevormwald",
  "Radolfzell",
  "Raguhn-Jeßnitz",
  "Rahden",
  "Rain",
  "Ramstein-Miesenbach",
  "Ranis",
  "Ransbach-Baumbach",
  "Rastatt",
  "Rastenberg",
  "Rathenow",
  "Ratingen",
  "Ratzeburg",
  "Rauenberg",
  "Raunheim",
  "Rauschenberg",
  "Ravensburg",
  "Ravenstein",
  "Recklinghausen",
  "Rees",
  "Regen",
  "Regensburg",
  "Regis-Breitingen",
  "Rehau",
  "Rehburg-Loccum",
  "Rehna",
  "Reichelsheim",
  "Reichenbach",
  "Reichenbach im Vogtland",
  "Reinbek",
  "Reinfeld",
  "Reinheim",
  "Remagen",
  "Remscheid",
  "Remseck",
  "Renchen",
  "Rendsburg",
  "Rennerod",
  "Renningen",
  "Rerik",
  "Rethem",
  "Reutlingen",
  "Rheda-Wiedenbrück",
  "Rhede",
  "Rheinau",
  "Rheinbach",
  "Rheinberg",
  "Rheinböllen",
  "Rheine",
  "Rheinfelden",
  "Rheinsberg",
  "Rheinstetten",
  "Rhens",
  "Rhinow",
  "Ribnitz-Damgarten",
  "Richtenberg",
  "Riedenburg",
  "Riedlingen",
  "Riedstadt",
  "Rieneck",
  "Riesa",
  "Rietberg",
  "Rinteln",
  "Röbel",
  "Rochlitz",
  "Rockenhausen",
  "Rodalben",
  "Rodenberg",
  "Rödental",
  "Rödermark",
  "Rodewisch",
  "Rodgau",
  "Roding",
  "Römhild",
  "Romrod",
  "Ronneburg",
  "Ronnenberg",
  "Rosbach vor der Höhe",
  "Rosenfeld",
  "Rosenheim",
  "Rosenthal",
  "Rösrath",
  "Roßleben-Wiehe",
  "Roßwein",
  "Rostock",
  "Rotenburg a. d.  Fulda",
  "Rotenburg an der Wümme",
  "Roth",
  "Rötha",
  "Röthenbach an der Pegnitz",
  "Rothenburg",
  "Rothenburg ob der Tauber",
  "Rothenfels",
  "Rottenburg a.d.Laaber",
  "Rottenburg am Neckar",
  "Röttingen",
  "Rottweil",
  "Rötz",
  "Rüdesheim",
  "Rudolstadt",
  "Ruhla",
  "Ruhland",
  "Runkel",
  "Rüsselsheim am Main",
  "Rutesheim",
  "Rüthen",
  "Saalburg-Ebersdorf",
  "Saalfeld",
  "Saarbrücken",
  "Saarburg",
  "Saarlouis",
  "Sachsenhagen",
  "Sachsenheim",
  "Salzgitter",
  "Salzkotten",
  "Salzwedel",
  "Sandau",
  "Sandersdorf-Brehna",
  "Sangerhausen",
  "Sankt Augustin",
  "Sankt Blasien",
  "Sankt Georgen im Schwarzwald",
  "Sankt Goar",
  "Sankt Goarshausen",
  "Sankt Ingbert",
  "Sankt Wendel",
  "Sarstedt",
  "Sassenberg",
  "Sassnitz",
  "Sayda, Saxony",
  "Schalkau",
  "Schauenstein",
  "Scheer",
  "Scheibenberg",
  "Scheinfeld",
  "Schelklingen",
  "Schenefeld",
  "Scheßlitz",
  "Schieder-Schwalenberg",
  "Schifferstadt",
  "Schillingsfürst",
  "Schiltach",
  "Schirgiswalde-Kirschau",
  "Schkeuditz",
  "Schkölen",
  "Schleiden",
  "Schleiz",
  "Schleswig",
  "Schlettau",
  "Schleusingen",
  "Schlieben",
  "Schlitz",
  "Schloß Holte-Stukenbrock",
  "Schlüchtern",
  "Schlüsselfeld",
  "Schmalkalden",
  "Schmallenberg",
  "Schmölln",
  "Schnackenburg",
  "Schnaittenbach",
  "Schneeberg",
  "Schneverdingen",
  "Schömberg",
  "Schönau",
  "Schönau im Schwarzwald",
  "Schönberg",
  "Schönebeck",
  "Schöneck",
  "Schönewalde",
  "Schongau",
  "Schöningen",
  "Schönsee",
  "Schönwald",
  "Schopfheim",
  "Schöppenstedt",
  "Schorndorf",
  "Schortens",
  "Schotten",
  "Schramberg",
  "Schraplau",
  "Schriesheim",
  "Schrobenhausen",
  "Schrozberg",
  "Schüttorf",
  "Schwaan",
  "Schwabach",
  "Schwäbisch Gmünd",
  "Schwäbisch Hall",
  "Schwabmünchen",
  "Schwaigern",
  "Schwalbach am Taunus",
  "Schwalmstadt",
  "Schwandorf",
  "Schwanebeck",
  "Schwarzatal",
  "Schwarzenbach a.d.Saale",
  "Schwarzenbach a.Wald",
  "Schwarzenbek",
  "Schwarzenberg",
  "Schwarzenborn",
  "Schwarzheide",
  "Schwedt",
  "Schweich",
  "Schweinfurt",
  "Schwelm",
  "Schwentinental",
  "Schwerin",
  "Schwerte",
  "Schwetzingen",
  "Sebnitz",
  "Seehausen",
  "Seeland",
  "Seelow",
  "Seelze",
  "Seesen",
  "Sehnde",
  "Seifhennersdorf",
  "Selb",
  "Selbitz",
  "Seligenstadt",
  "Selm",
  "Selters",
  "Senden",
  "Sendenhorst",
  "Senftenberg",
  "Seßlach",
  "Siegburg",
  "Siegen",
  "Sigmaringen",
  "Simbach am Inn",
  "Simmern",
  "Sindelfingen",
  "Singen",
  "Sinsheim",
  "Sinzig",
  "Soest",
  "Solingen",
  "Solms",
  "Soltau",
  "Sömmerda",
  "Sondershausen",
  "Sonneberg",
  "Sonnewalde",
  "Sonthofen",
  "Sontra",
  "Spaichingen",
  "Spalt",
  "Spangenberg",
  "Speicher",
  "Spenge",
  "Speyer",
  "Spremberg",
  "Springe",
  "Sprockhövel",
  "Stadt Tegernsee",
  "Stadt Wehlen",
  "Stadtallendorf",
  "Stadtbergen",
  "Stadthagen",
  "Stadtilm",
  "Stadtlohn",
  "Stadtoldendorf",
  "Stadtprozelten",
  "Stadtroda",
  "Stadtsteinach",
  "Starnberg",
  "Staßfurt",
  "Staufen im Breisgau",
  "Staufenberg",
  "Stavenhagen",
  "Stein",
  "Steinach",
  "Steinau an der Straße",
  "Steinbach",
  "Steinbach-Hallenberg",
  "Steinfurt",
  "Steinheim",
  "Steinheim an der Murr",
  "Stendal",
  "Sternberg",
  "Stockach",
  "Stolberg",
  "Stollberg",
  "Stolpen",
  "Storkow",
  "Stößen",
  "Straelen",
  "Stralsund",
  "Strasburg",
  "Straubing",
  "Strausberg",
  "Strehla",
  "Stromberg",
  "Stühlingen",
  "Stutensee",
  "Stuttgart",
  "Südliches Anhalt",
  "Suhl",
  "Sulingen",
  "Sulz am Neckar",
  "Sulzbach",
  "Sulzbach-Rosenberg",
  "Sulzburg",
  "Sundern",
  "Süßen",
  "Syke",
  "Tambach-Dietharz",
  "Tangerhütte",
  "Tangermünde",
  "Tann (Rhön)",
  "Tanna",
  "Tauberbischofsheim",
  "Taucha",
  "Taunusstein",
  "Tecklenburg",
  "Telgte",
  "Teltow",
  "Templin",
  "Tengen",
  "Tessin",
  "Teterow",
  "Tettnang",
  "Teublitz",
  "Teuchern",
  "Teupitz",
  "Teuschnitz",
  "Thale",
  "Thalheim",
  "Thannhausen",
  "Tharandt",
  "Themar",
  "Thum",
  "Tirschenreuth",
  "Titisee-Neustadt",
  "Tittmoning",
  "Todtnau",
  "Töging am Inn",
  "Tönisvorst",
  "TönningTønning / Taning",
  "Torgau",
  "Torgelow",
  "Tornesch",
  "Traben-Trarbach",
  "Traunreut",
  "Traunstein",
  "Trebbin",
  "Trebsen",
  "Treffurt",
  "Trendelburg",
  "Treuchtlingen",
  "Treuen",
  "Treuenbrietzen",
  "Triberg im Schwarzwald",
  "Tribsees",
  "Trier",
  "Triptis",
  "Trochtelfingen",
  "Troisdorf",
  "Trossingen",
  "Trostberg",
  "Tübingen",
  "Tuttlingen",
  "Twistringen",
  "Übach-Palenberg",
  "Überlingen",
  "Uebigau-Wahrenbrück",
  "Ueckermünde",
  "Uelzen",
  "Uetersen",
  "Uffenheim",
  "Uhingen",
  "Ulm",
  "Ulmen",
  "Ulrichstein",
  "Ummerstadt",
  "Unkel",
  "Unna",
  "Unterschleißheim",
  "Usedom",
  "Usingen",
  "Uslar",
  "Vacha",
  "Vaihingen an der Enz",
  "Vallendar",
  "Varel",
  "Vechta",
  "Velbert",
  "Velburg",
  "Velden",
  "Velen",
  "Vellberg",
  "Vellmar",
  "Velten",
  "Verden an der Aller",
  "Veringenstadt",
  "Verl",
  "Versmold",
  "Vetschau",
  "Viechtach",
  "Viernheim",
  "Viersen",
  "Villingen-Schwenningen",
  "Vilsbiburg",
  "Vilseck",
  "Vilshofen an der Donau",
  "Visselhövede",
  "Vlotho",
  "Voerde",
  "Vogtsburg",
  "Vohburg a.d.Donau",
  "Vohenstrauß",
  "Vöhrenbach",
  "Vöhringen",
  "Volkach",
  "Völklingen",
  "Volkmarsen",
  "Vreden",
  "Wachenheim",
  "Wächtersbach",
  "Wadern",
  "Waghäusel",
  "Wahlstedt",
  "Waiblingen",
  "Waibstadt",
  "Waischenfeld",
  "Waldbröl",
  "Waldeck",
  "Waldenbuch",
  "Waldenburg",
  "Waldershof",
  "Waldheim",
  "Waldkappel",
  "Waldkirch",
  "Waldkirchen",
  "Waldkraiburg",
  "Waldmohr",
  "Waldmünchen",
  "Waldsassen",
  "Waldshut-Tiengen",
  "Walldorf",
  "Walldürn",
  "Wallenfels",
  "Walsrode",
  "Waltershausen",
  "Waltrop",
  "Wanfried",
  "Wangen im Allgäu",
  "Wanzleben-Börde",
  "Warburg",
  "Waren",
  "Warendorf",
  "Warin",
  "Warstein",
  "Wassenberg",
  "Wasserburg am Inn",
  "Wassertrüdingen",
  "Wasungen",
  "Wedel",
  "Weener",
  "Wegberg",
  "Wegeleben",
  "Wehr",
  "Weida",
  "Weiden in der Oberpfalz",
  "Weikersheim",
  "Weil am Rhein, Germany",
  "Weil der Stadt",
  "Weilburg",
  "Weilheim an der Teck",
  "Weilheim in Oberbayern",
  "Weimar",
  "Weingarten",
  "Weinheim",
  "Weinsberg",
  "Weinstadt",
  "Weismain",
  "Weißenberg",
  "Weißenburg in Bayern",
  "Weißenfels",
  "Weißenhorn",
  "Weißensee",
  "Weißenstadt",
  "Weißenthurm",
  "Weißwasser",
  "Weiterstadt",
  "Welzheim",
  "Welzow",
  "Wemding",
  "Wendlingen",
  "Werben",
  "Werdau",
  "Werder (Havel)",
  "Werdohl",
  "Werl",
  "Werlte",
  "Wermelskirchen",
  "Wernau",
  "Werne",
  "Werneuchen",
  "Wernigerode",
  "Werra-Suhl-Tal",
  "Wertheim",
  "Werther (Westf.)",
  "Wertingen",
  "Wesel",
  "Wesenberg",
  "Wesselburen",
  "Wesseling",
  "Westerburg",
  "Westerstede",
  "Wetter",
  "Wetter (Hessen)",
  "Wettin-Löbejün",
  "Wetzlar",
  "Widdern",
  "Wiehl",
  "Wiesbaden",
  "Wiesensteig",
  "Wiesloch",
  "Wiesmoor",
  "Wildau",
  "Wildberg",
  "Wildenfels",
  "Wildeshausen",
  "Wilhelmshaven",
  "Wilkau-Haßlau",
  "Willebadessen",
  "Willich",
  "Wilsdruff",
  "Wilster",
  "Wilthen",
  "Windischeschenbach",
  "Windsbach",
  "Winnenden",
  "Winsen",
  "Winterberg",
  "Wipperfürth",
  "Wirges",
  "Wismar",
  "Wissen",
  "Witten",
  "Wittenberg",
  "Wittenberge",
  "Wittenburg",
  "Wittichenau",
  "Wittingen",
  "Wittlich",
  "Wittmund",
  "Wittstock",
  "Witzenhausen, Germany",
  "Woldegk",
  "Wolfach",
  "Wolfenbüttel",
  "Wolfhagen",
  "Wolframs-Eschenbach",
  "Wolfratshausen",
  "Wolfsburg",
  "Wolfstein",
  "Wolgast",
  "Wolkenstein",
  "Wolmirstedt",
  "Worms",
  "Wörrstadt",
  "Wörth am Main",
  "Wörth am Rhein",
  "Wörth an der Donau",
  "Wriezen",
  "Wülfrath",
  "Wunsiedel",
  "Wunstorf",
  "Wuppertal",
  "Würselen",
  "Wurzbach",
  "Würzburg",
  "Wurzen",
  "Wustrow",
  "Wyk auf Föhra Wik / Vyk",
  "Xanten",
  "Zahna-Elster",
  "Zarrentin am Schaalsee",
  "Zehdenick",
  "Zeil am Main",
  "Zeitz",
  "Zell",
  "Zell am Harmersbach",
  "Zell im Wiesental",
  "Zella-Mehlis",
  "Zerbst",
  "Zeulenroda-Triebes",
  "Zeven",
  "Ziegenrück",
  "Zierenberg",
  "Ziesar",
  "Zirndorf",
  "Zittau",
  "Zörbig",
  "Zossen",
  "Zschopau",
  "Zülpich",
  "Zweibrücken",
  "Zwenkau",
  "Zwickau",
  "Zwiesel",
  "Zwingenberg",
  "Zwönitz"
];
